services:
  db:
    # name: db
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - "5433:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
